### ISSUE TITLE
Docker Configuration

### ISSUE THREAD

**Issue by MrA1** [davidahouse/stampede-server#293]
We should have a production ready docker image or a docker compose configuration for easy user setup.

AC:
- Redis, Postgres included in configuration / compose
- Should persist data on startup/shutdown
- Image on Docker Hub

**Comment by davidahouse** [comment]
Docker images now getting published to docker hub. Also a full working example using docker compose that persists the data can be found here:
https://github.com/davidahouse/stampede-example
